### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by cyrto** [Programming-With-Love/dd1024#2]
C:\Users\xxxxx\AppData\Roaming\npm\node_modules\dd1024\lib\api\site\javzw.com.js:12
  
static SiteInfo = {

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:743:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\dd1024\lib\api\index.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)

**Comment by d1y** [comment]
> C:\Users\xxxxx\AppData\Roaming\npm\node_modules\dd1024\lib\api\site\javzw.com.js:12
> 
> static SiteInfo = {
> 
> SyntaxError: Unexpected token =
> at Module._compile (internal/modules/cjs/loader.js:743:23)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
> at Module.load (internal/modules/cjs/loader.js:666:32)
> at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
> at Function.Module._load (internal/modules/cjs/loader.js:598:3)
> at Module.require (internal/modules/cjs/loader.js:705:19)
> at require (internal/modules/cjs/helpers.js:14:16)
> at Object. (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\dd1024\lib\api\index.js:2:15)
> at Module._compile (internal/modules/cjs/loader.js:799:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)

可以告知一下你的操作流程吗，尝试一下npm全局安装看看

cnpm i -g dd1024

**Comment by cyrto** [comment]
> > C:\Users\xxxxx\AppData\Roaming\npm\node_modules\dd1024\lib\api\site\javzw.com.js:12
> > static SiteInfo = {
> > SyntaxError: Unexpected token =
> > at Module._compile (internal/modules/cjs/loader.js:743:23)
> > at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
> > at Module.load (internal/modules/cjs/loader.js:666:32)
> > at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
> > at Function.Module._load (internal/modules/cjs/loader.js:598:3)
> > at Module.require (internal/modules/cjs/loader.js:705:19)
> > at require (internal/modules/cjs/helpers.js:14:16)
> > at Object. (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\dd1024\lib\api\index.js:2:15)
> > at Module._compile (internal/modules/cjs/loader.js:799:30)
> > at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
> 
> 可以告知一下你的操作流程吗，尝试一下npm全局安装看看
> 
> cnpm i -g dd1024

我先用npm装了一遍，执行dd1024 xxx报错，然后再用cnpm装了一遍，执行还是一样😥

**Comment by d1y** [comment]
> > > C:\Users\xxxxx\AppData\Roaming\npm\node_modules\dd1024\lib\api\site\javzw.com.js:12
> > > static SiteInfo = {
> > > SyntaxError: Unexpected token =
> > > at Module._compile (internal/modules/cjs/loader.js:743:23)
> > > at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
> > > at Module.load (internal/modules/cjs/loader.js:666:32)
> > > at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
> > > at Function.Module._load (internal/modules/cjs/loader.js:598:3)
> > > at Module.require (internal/modules/cjs/loader.js:705:19)
> > > at require (internal/modules/cjs/helpers.js:14:16)
> > > at Object. (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\dd1024\lib\api\index.js:2:15)
> > > at Module._compile (internal/modules/cjs/loader.js:799:30)
> > > at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
> > 
> > 
> > 可以告知一下你的操作流程吗，尝试一下npm全局安装看看
> > cnpm i -g dd1024
> 
> 我先用npm装了一遍，执行dd1024 xxx报错，然后再用cnpm装了一遍，执行还是一样😥

方便告知一下 `nodejs` and `npm` 版本吗

**Comment by QuanBaia** [comment]
nodejs 版本 v10.16.3
npm 版本 6.9.0
`C:\Users\Administrator\AppData\Roaming\npm\node_modules\dd1024\lib\api\site\javzw.com.js:11
  static SiteInfo = {
                  ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\dd1024\lib\api\index.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)`
报同样的错误
